name: Deploy app
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'
  checks: 'write'
env:
  PROJECT_ID: profound-coyote-418718

jobs:
  # <-------------------  BUILD IMAGE -------------------->
  build-image:
    name: Build Image
    runs-on: self-hosted
    outputs:
      image-name: ${{ steps.build-image.outputs.imageFullName }}
      image-tag: ${{ steps.build-image.outputs.tags }}
      branch: ${{ env.GITHUB_REF_SLUG_URL }}
    steps:
      # PREP STEPS
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v4

      - name: Authenticate to GCP (SA Key)
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPLICATION_SA }}
          export_default_credentials: true

      # BUILD AND PUSH THE IMAGE
      - name: Build & Push Image
        id: build-image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.PROJECT_ID }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}
          registry: "eu.gcr.io"
          username: _json_key
          password: ${{ secrets.APPLICATION_SA }}

  # <------------------ DEPLOY APP to GCP ------------------->
  deploy-app:
    name: Deploy app
    needs: build-image
    runs-on: self-hosted
    outputs:
      env_url: ${{ steps.deploy.outputs.url }}
    environment:
      name: ${{ needs.build-image.outputs.branch }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v4

      - name: Authenticate to GCP (SA Key)
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPLICATION_SA }}

      - name: Deploy to Cloud Run
        id: deploy
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}" --quiet
          mkdir temp_source && cp main.py requirements.txt temp_source/
          gcloud functions deploy my-python-app \
              --region=europe-west1 \
              --runtime=python39 \
              --source=temp_source \
              --memory=1024MB \
              --timeout=300 \
              --trigger-http \
              --allow-unauthenticated