name: Deploy app
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'
  checks: 'write'
env:
  PROJECT_ID: profound-coyote-418718

jobs:

  # <------------------ DEPLOY APP to GCP ------------------->
  deploy-app:
    name: Deploy app
    needs: build-image
    runs-on: self-hosted
    outputs:
      env_url: ${{ steps.deploy.outputs.url }}
    environment:
      name: ${{ needs.build-image.outputs.branch }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v4

      - name: Authenticate to GCP (SA Key)
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPLICATION_SA }}

      - name: Deploy to Cloud Run
        id: deploy
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}" --quiet
          mkdir temp_source && cp main.py requirements.txt temp_source/
          gcloud functions deploy my-python-app \
              --region=europe-west1 \
              --runtime=python39 \
              --source=temp_source \
              --memory=1024MB \
              --timeout=300 \
              --trigger-http \
              --allow-unauthenticated