name: Deploy app
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'
  checks: 'write'
env:
  PROJECT_ID: profound-coyote-418718

jobs:
  # <------------------ DEPLOY APP to GCP ------------------->
  deploy-app:
    name: Deploy app
    runs-on: self-hosted
    outputs:
      env_url: ${{ steps.deploy.outputs.url }}
    environment:
      name: ${{ needs.build-image.outputs.branch }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v4

      - name: Authenticate to GCP (SA Key)
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPLICATION_SA }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud function
        id: deploy
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}" --quiet
          mkdir temp_src_function && cp main.py requirements.txt temp_src_function/
          gcloud functions deploy my-python-app-test \
              --gen2
              --region=europe-west1 \
              --runtime=python312 \
              --source=temp_src_function \
              --service-account deploy-python-app@profound-coyote-418718.iam.gserviceaccount.com \
              --memory=256MB \
              --timeout=300 \
              --trigger-http \
              --entry-point=hello_http
              --allow-unauthenticated
          
